# .github/workflows/build.yml
name: Build

on:
  pull_request:
    branches: [main, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make
      - name: Tests
        env:
          TERM: xterm-256color
        run: make tests
